// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoMVC3.Models;

#nullable disable

namespace ProyectoMVC3.Migrations
{
    [DbContext(typeof(AutorDbContext))]
    [Migration("20220720131049_Migracion Autor")]
    partial class MigracionAutor
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ProyectoMVC3.Models.Autor", b =>
                {
                    b.Property<string>("id_autor")
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Genero")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("apellido")
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("ciudad")
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("cod_postal")
                        .HasColumnType("int");

                    b.Property<string>("direccion")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("estado")
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("pais")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("telefono")
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("id_autor");

                    b.ToTable("Autores");
                });
#pragma warning restore 612, 618
        }
    }
}
